In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
from numpy._core.numerictypes import datetime64

In [14]:

df = pd.read_csv(
    r"C:\Ki_4\Domain Banking\Financial Transactions\transactions_data.csv", 
    dtype={
        "id": str, 
        "client_id": str, 
        "card_id": str, 
        "use_chip": str, 
        "merchant_id": str,
        "merchant_city": str, 
        "merchant_state": str, 
        "zip": str, 
        "mcc": str, 
        "errors": str
    }, 
    parse_dates=["date"]
)


df['amount'] = df['amount'].str.replace('$', '', regex=False).astype(float)


df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [15]:
df.info()
print(df.isnull().sum())
print("description of the dataset:")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13305915 entries, 0 to 13305914
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   id              object
 1   date            datetime64[ns]
 2   client_id       object
 3   card_id         object
 4   amount          float64
 5   use_chip        object
 6   merchant_id     object
 7   merchant_city   object
 8   merchant_state  object
 9   zip             object
 10  mcc             object
 11  errors          object
dtypes: datetime64[ns](1), float64(1), object(10)
memory usage: 1.2+ GB
id                       0
date                     0
client_id                0
card_id                  0
amount                   0
use_chip                 0
merchant_id              0
merchant_city            0
merchant_state     1563700
zip                1652706
mcc                      0
errors            13094522
dtype: int64
description of the dataset:
                                date        amount
count                       13305915  1.330592e+07
mean   2015-01-06 06:50:27.604354816  4.297604e+01
min              2010-01-01 00:01:00 -5.000000e+02
25%              2012-08-08 21:43:00  8.930000e+00
50%              2015-01-22 12:17:00  2.899000e+01
75%              2017-06-13 17:45:00  6.371000e+01
max              2019-10-31 23:59:00  6.820200e+03
std                              NaN  8.165575e+01

In [18]:

df_users = pd.read_csv(r"C:\Ki_4\Domain Banking\Financial Transactions\users_data.csv")


cols_to_clean = ['per_capita_income', 'yearly_income', 'total_debt']

for col in cols_to_clean:
    df_users[col] = df_users[col].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

print(f"Kích thước bảng Users: {df_users.shape[0]:,} dòng, {df_users.shape[1]} cột.")
print("\nThông tin dữ liệu trống (Null):")
print(df_users.isnull().sum())


df_users.head()
df.describe

Kích thước bảng Users: 2,000 dòng, 14 cột.

Thông tin dữ liệu trống (Null):
id                   0
current_age          0
retirement_age       0
birth_year           0
birth_month          0
gender               0
address              0
latitude             0
longitude            0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
dtype: int64

<bound method NDFrame.describe of                 id                date client_id card_id  amount  \
0          7475327 2010-01-01 00:01:00      1556    2972  -77.00
1          7475328 2010-01-01 00:02:00       561    4575   14.57
2          7475329 2010-01-01 00:02:00      1129     102   80.00
3          7475331 2010-01-01 00:05:00       430    2860  200.00
4          7475332 2010-01-01 00:06:00       848    3915   46.41
...            ...                 ...       ...     ...     ...
13305910  23761868 2019-10-31 23:56:00      1718    2379    1.11
13305911  23761869 2019-10-31 23:56:00      1766    2066   12.80
13305912  23761870 2019-10-31 23:57:00       199    1031   40.44
13305913  23761873 2019-10-31 23:58:00      1986    5443    4.00
13305914  23761874 2019-10-31 23:59:00       489    5697   12.88

                    use_chip merchant_id merchant_city merchant_state  \
0          Swipe Transaction       59935        Beulah             ND
1          Swipe Transaction       67570    Bettendorf             IA
2          Swipe Transaction       27092         Vista             CA
3          Swipe Transaction       27092   Crown Point             IN
4          Swipe Transaction       13051       Harwood             MD
...                      ...         ...           ...            ...
13305910    Chip Transaction       86438   West Covina             CA
13305911  Online Transaction       39261        ONLINE            NaN
13305912   Swipe Transaction        2925         Allen             TX
13305913    Chip Transaction       46284     Daly City             CA
13305914    Chip Transaction       24658    Greenbrier             TN

              zip   mcc errors
0         58523.0  5499    NaN
1         52722.0  5311    NaN
2         92084.0  4829    NaN
3         46307.0  4829    NaN
4         20776.0  5813    NaN
...           ...   ...    ...
13305910  91792.0  5499    NaN
13305911      NaN  5815    NaN
13305912  75002.0  4900    NaN
13305913  94014.0  5411    NaN
13305914  37073.0  5921    NaN

[13305915 rows x 12 columns]>

In [17]:

df_cards = pd.read_csv(
    r"C:\Ki_4\Domain Banking\Financial Transactions\cards_data.csv",
    dtype={'id': str, 'client_id': str}
)

df_cards['credit_limit'] = df_cards['credit_limit'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

print(f"Kích thước bảng Cards: {df_cards.shape[0]:,} dòng, {df_cards.shape[1]} cột.")
print("\nThông tin dữ liệu trống (Null):")
print(df_cards.isnull().sum())


df_cards.head()

Kích thước bảng Cards: 6,146 dòng, 13 cột.

Thông tin dữ liệu trống (Null):
id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
card_on_dark_web         0
dtype: int64

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,24295.0,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,21968.0,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,46414.0,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,12400.0,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,28.0,09/2008,2009,No

XỬ lý dữ liệu missing data cho Transaction

In [19]:


df['errors'] = df['errors'].fillna('No Error')


df['merchant_state'] = df['merchant_state'].fillna('Online/International')
df['zip'] = df['zip'].fillna('Online/International')

print("Kiểm tra lại xem còn ô nào bị Null không:")
print(df.isnull().sum())

Kiểm tra lại xem còn ô nào bị Null không:
id                0
date              0
client_id         0
card_id           0
amount            0
use_chip          0
merchant_id       0
merchant_city     0
merchant_state    0
zip               0
mcc               0
errors            0
dtype: int64

Xử lý các file json

In [22]:


with open(r"C:\Ki_4\Domain Banking\Financial Transactions\mcc_codes.json", "r") as f:
    mcc_data = json.load(f)


df_mcc = pd.DataFrame(list(mcc_data.items()), columns=['mcc', 'mcc_description'])

print(f"Tổng số mã ngành hàng: {df_mcc.shape[0]} mã.")


df_mcc.head()

Tổng số mã ngành hàng: 109 mã.

    mcc                       mcc_description
0  5812         Eating Places and Restaurants
1  5541                      Service Stations
2  7996  Amusement Parks, Carnivals, Circuses
3  5411          Grocery Stores, Supermarkets
4  4784                 Tolls and Bridge Fees

In [24]:


with open(r"C:\Ki_4\Domain Banking\Financial Transactions\train_fraud_labels.json", "r") as f:
    fraud_data = json.load(f)


inner_data = list(fraud_data.values())[0]


df_labels = pd.DataFrame(list(inner_data.items()), columns=['id', 'is_fraud'])

print(f"Tổng số nhãn giao dịch: {df_labels.shape[0]:,} dòng.")

print("\nfraud rate")

fraud_distribution = df_labels['is_fraud'].value_counts(normalize=True) * 100
print(fraud_distribution)

Tổng số nhãn giao dịch: 8,914,963 dòng.

fraud rate
is_fraud
No     99.850454
Yes     0.149546
Name: proportion, dtype: float64

Tạo bảng fact

In [25]:


df_master = pd.merge(df, df_labels, on='id', how='left')


df_master['is_fraud'] = df_master['is_fraud'].map({'Yes': 1, 'No': 0}).fillna(0).astype(int)

print(f"Kích thước bảng Master: {df_master.shape[0]:,} dòng, {df_master.shape[1]} cột.")
print("\nKiểm tra lại phân phối số lượng Gian lận (1) và Bình thường (0):")
print(df_master['is_fraud'].value_counts())


import os
os.makedirs("clean_data", exist_ok=True)
print("\nĐang lưu file fact_transactions.parquet")
df_master.to_parquet("clean_data/fact_transactions.parquet", index=False)

Kích thước bảng Master: 13,305,915 dòng, 13 cột.

Kiểm tra lại phân phối số lượng Gian lận (1) và Bình thường (0):
is_fraud
0    13292583
1       13332
Name: count, dtype: int64

Đang lưu file fact_transactions.parquet

In [26]:

df_users.to_parquet("clean_data/dim_users.parquet", index=False)


df_cards.to_parquet("clean_data/dim_cards.parquet", index=False)


df_mcc.to_parquet("clean_data/dim_mcc.parquet", index=False)

Đẩy lên BQ

In [1]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account



key_path = r"C:\Ki_4\Domain Banking\Financial Transactions\jda-k1-2afad6d8f47e.json"
project_id = "jda-k1" 
dataset_id = "duonglh_bigproject"


credentials = service_account.Credentials.from_service_account_file(key_path)
client = bigquery.Client(credentials=credentials, project=project_id)


tables_to_upload = {
    "dim_mcc": "clean_data/dim_mcc.parquet",
    "dim_users": "clean_data/dim_users.parquet",
    "dim_cards": "clean_data/dim_cards.parquet",
    "fact_transactions": "clean_data/fact_transactions.parquet"
}


for table_name, file_path in tables_to_upload.items():

    df = pd.read_parquet(file_path)
    
    table_ref = f"{project_id}.{dataset_id}.{table_name}"
    

    job_config = bigquery.LoadJobConfig(
        write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE,
        autodetect=True
    )
    

    job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
    

    job.result() 


print("\nProcess completed")

Process completed